// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/postgres/PostgresRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "router-manager/internal/model"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockPostgresRepo is a mock of PostgresRepo interface.
type MockPostgresRepo struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresRepoMockRecorder
}

// MockPostgresRepoMockRecorder is the mock recorder for MockPostgresRepo.
type MockPostgresRepoMockRecorder struct {
	mock *MockPostgresRepo
}

// NewMockPostgresRepo creates a new mock instance.
func NewMockPostgresRepo(ctrl *gomock.Controller) *MockPostgresRepo {
	mock := &MockPostgresRepo{ctrl: ctrl}
	mock.recorder = &MockPostgresRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresRepo) EXPECT() *MockPostgresRepoMockRecorder {
	return m.recorder
}

// ChangeStatusByRouterId mocks base method.
func (m *MockPostgresRepo) ChangeStatusByRouterId(ctx context.Context, routerId uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatusByRouterId", ctx, routerId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatusByRouterId indicates an expected call of ChangeStatusByRouterId.
func (mr *MockPostgresRepoMockRecorder) ChangeStatusByRouterId(ctx, routerId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatusByRouterId", reflect.TypeOf((*MockPostgresRepo)(nil).ChangeStatusByRouterId), ctx, routerId, status)
}

// FindRouterByRouterId mocks base method.
func (m *MockPostgresRepo) FindRouterByRouterId(ctx context.Context, id string) (*model.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRouterByRouterId", ctx, id)
	ret0, _ := ret[0].(*model.Router)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRouterByRouterId indicates an expected call of FindRouterByRouterId.
func (mr *MockPostgresRepoMockRecorder) FindRouterByRouterId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRouterByRouterId", reflect.TypeOf((*MockPostgresRepo)(nil).FindRouterByRouterId), ctx, id)
}

// GetCommandsByRouterId mocks base method.
func (m *MockPostgresRepo) GetCommandsByRouterId(ctx context.Context, routerId uuid.UUID) ([]model.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommandsByRouterId", ctx, routerId)
	ret0, _ := ret[0].([]model.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommandsByRouterId indicates an expected call of GetCommandsByRouterId.
func (mr *MockPostgresRepoMockRecorder) GetCommandsByRouterId(ctx, routerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommandsByRouterId", reflect.TypeOf((*MockPostgresRepo)(nil).GetCommandsByRouterId), ctx, routerId)
}

// SaveCommand mocks base method.
func (m *MockPostgresRepo) SaveCommand(ctx context.Context, cmd *model.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommand", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommand indicates an expected call of SaveCommand.
func (mr *MockPostgresRepoMockRecorder) SaveCommand(ctx, cmd interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommand", reflect.TypeOf((*MockPostgresRepo)(nil).SaveCommand), ctx, cmd)
}

// SaveRouter mocks base method.
func (m *MockPostgresRepo) SaveRouter(ctx context.Context, router *model.Router) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRouter", ctx, router)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRouter indicates an expected call of SaveRouter.
func (mr *MockPostgresRepoMockRecorder) SaveRouter(ctx, router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRouter", reflect.TypeOf((*MockPostgresRepo)(nil).SaveRouter), ctx, router)
}
