// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0--rc2
// source: command_service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// информация о роутере
type Router struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Router) Reset() {
	*x = Router{}
	mi := &file_command_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Router) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Router) ProtoMessage() {}

func (x *Router) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Router.ProtoReflect.Descriptor instead.
func (*Router) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{0}
}

func (x *Router) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *Router) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// тело отправки команды роутеру
type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routers       []*Router              `protobuf:"bytes,1,rep,name=routers,proto3" json:"routers,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_command_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{1}
}

func (x *SendCommandRequest) GetRouters() []*Router {
	if x != nil {
		return x.Routers
	}
	return nil
}

func (x *SendCommandRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

// тело запроса команд роутера
type PollRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollRequest) Reset() {
	*x = PollRequest{}
	mi := &file_command_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollRequest) ProtoMessage() {}

func (x *PollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollRequest.ProtoReflect.Descriptor instead.
func (*PollRequest) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{2}
}

func (x *PollRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *PollRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

// тело запроса "ack"
type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	CommandType   string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_command_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{3}
}

func (x *AckRequest) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *AckRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *AckRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

// ответ на отправку команды = статус
type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Id            []string               `protobuf:"bytes,2,rep,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_command_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{4}
}

func (x *SendCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SendCommandResponse) GetId() []string {
	if x != nil {
		return x.Id
	}
	return nil
}

// информация о команде роутера
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// список команд роутера
type PollResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResponse) Reset() {
	*x = PollResponse{}
	mi := &file_command_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResponse) ProtoMessage() {}

func (x *PollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResponse.ProtoReflect.Descriptor instead.
func (*PollResponse) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{6}
}

func (x *PollResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// ответ на "ack" = статус 'ACKED'
type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_command_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_command_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_command_service_proto_rawDescGZIP(), []int{7}
}

func (x *AckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_command_service_proto protoreflect.FileDescriptor

const file_command_service_proto_rawDesc = "" +
	"\n" +
	"\x15command_service.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"J\n" +
	"\x06Router\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\"`\n" +
	"\x12SendCommandRequest\x12'\n" +
	"\arouters\x18\x01 \x03(\v2\r.proto.RouterR\arouters\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\"O\n" +
	"\vPollRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\"q\n" +
	"\n" +
	"AckRequest\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\"=\n" +
	"\x13SendCommandResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x03(\tR\x02id\"\x91\x01\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\":\n" +
	"\fPollResponse\x12*\n" +
	"\bcommands\x18\x01 \x03(\v2\x0e.proto.CommandR\bcommands\"%\n" +
	"\vAckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xa8\x02\n" +
	"\x0eCommandService\x12e\n" +
	"\vSendCommand\x12\x19.proto.SendCommandRequest\x1a\x1a.proto.SendCommandResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/send_command\x12Y\n" +
	"\fPollCommands\x12\x12.proto.PollRequest\x1a\x13.proto.PollResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/v1/commands/poll\x12T\n" +
	"\n" +
	"AckCommand\x12\x11.proto.AckRequest\x1a\x12.proto.AckResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/commands/ackB\x0fZ\r./internal/pbb\x06proto3"

var (
	file_command_service_proto_rawDescOnce sync.Once
	file_command_service_proto_rawDescData []byte
)

func file_command_service_proto_rawDescGZIP() []byte {
	file_command_service_proto_rawDescOnce.Do(func() {
		file_command_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_service_proto_rawDesc), len(file_command_service_proto_rawDesc)))
	})
	return file_command_service_proto_rawDescData
}

var file_command_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_command_service_proto_goTypes = []any{
	(*Router)(nil),                // 0: proto.Router
	(*SendCommandRequest)(nil),    // 1: proto.SendCommandRequest
	(*PollRequest)(nil),           // 2: proto.PollRequest
	(*AckRequest)(nil),            // 3: proto.AckRequest
	(*SendCommandResponse)(nil),   // 4: proto.SendCommandResponse
	(*Command)(nil),               // 5: proto.Command
	(*PollResponse)(nil),          // 6: proto.PollResponse
	(*AckResponse)(nil),           // 7: proto.AckResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_command_service_proto_depIdxs = []int32{
	0, // 0: proto.SendCommandRequest.routers:type_name -> proto.Router
	8, // 1: proto.Command.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: proto.PollResponse.commands:type_name -> proto.Command
	1, // 3: proto.CommandService.SendCommand:input_type -> proto.SendCommandRequest
	2, // 4: proto.CommandService.PollCommands:input_type -> proto.PollRequest
	3, // 5: proto.CommandService.AckCommand:input_type -> proto.AckRequest
	4, // 6: proto.CommandService.SendCommand:output_type -> proto.SendCommandResponse
	6, // 7: proto.CommandService.PollCommands:output_type -> proto.PollResponse
	7, // 8: proto.CommandService.AckCommand:output_type -> proto.AckResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_command_service_proto_init() }
func file_command_service_proto_init() {
	if File_command_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_service_proto_rawDesc), len(file_command_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_command_service_proto_goTypes,
		DependencyIndexes: file_command_service_proto_depIdxs,
		MessageInfos:      file_command_service_proto_msgTypes,
	}.Build()
	File_command_service_proto = out.File
	file_command_service_proto_goTypes = nil
	file_command_service_proto_depIdxs = nil
}
