// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/redis/RedisRepository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "router-manager/internal/model"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockRedisRepo is a mock of RedisRepo interface.
type MockRedisRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRedisRepoMockRecorder
}

// MockRedisRepoMockRecorder is the mock recorder for MockRedisRepo.
type MockRedisRepoMockRecorder struct {
	mock *MockRedisRepo
}

// NewMockRedisRepo creates a new mock instance.
func NewMockRedisRepo(ctrl *gomock.Controller) *MockRedisRepo {
	mock := &MockRedisRepo{ctrl: ctrl}
	mock.recorder = &MockRedisRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRedisRepo) EXPECT() *MockRedisRepoMockRecorder {
	return m.recorder
}

// ChangeStatusByRouterId mocks base method.
func (m *MockRedisRepo) ChangeStatusByRouterId(ctx context.Context, routerId uuid.UUID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeStatusByRouterId", ctx, routerId, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangeStatusByRouterId indicates an expected call of ChangeStatusByRouterId.
func (mr *MockRedisRepoMockRecorder) ChangeStatusByRouterId(ctx, routerId, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeStatusByRouterId", reflect.TypeOf((*MockRedisRepo)(nil).ChangeStatusByRouterId), ctx, routerId, status)
}

// FindCommandsByRouterId mocks base method.
func (m *MockRedisRepo) FindCommandsByRouterId(ctx context.Context, routerId uuid.UUID) ([]model.Command, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCommandsByRouterId", ctx, routerId)
	ret0, _ := ret[0].([]model.Command)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCommandsByRouterId indicates an expected call of FindCommandsByRouterId.
func (mr *MockRedisRepoMockRecorder) FindCommandsByRouterId(ctx, routerId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCommandsByRouterId", reflect.TypeOf((*MockRedisRepo)(nil).FindCommandsByRouterId), ctx, routerId)
}

// FindRouterByRouterId mocks base method.
func (m *MockRedisRepo) FindRouterByRouterId(ctx context.Context, id string) (*model.Router, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindRouterByRouterId", ctx, id)
	ret0, _ := ret[0].(*model.Router)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindRouterByRouterId indicates an expected call of FindRouterByRouterId.
func (mr *MockRedisRepoMockRecorder) FindRouterByRouterId(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindRouterByRouterId", reflect.TypeOf((*MockRedisRepo)(nil).FindRouterByRouterId), ctx, id)
}

// SaveCommand mocks base method.
func (m *MockRedisRepo) SaveCommand(ctx context.Context, command *model.Command) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCommand", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCommand indicates an expected call of SaveCommand.
func (mr *MockRedisRepoMockRecorder) SaveCommand(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCommand", reflect.TypeOf((*MockRedisRepo)(nil).SaveCommand), ctx, command)
}

// SaveRouter mocks base method.
func (m *MockRedisRepo) SaveRouter(ctx context.Context, router *model.Router) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRouter", ctx, router)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveRouter indicates an expected call of SaveRouter.
func (mr *MockRedisRepoMockRecorder) SaveRouter(ctx, router interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRouter", reflect.TypeOf((*MockRedisRepo)(nil).SaveRouter), ctx, router)
}
